DROP TABLE IF EXISTS ROLE;
CREATE TABLE `ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT '角色名称',
  `ROLE_CODE` varchar(20) NOT NULL COMMENT '角色代码',
  `ROLE_DESC` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT '角色描述',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ROLE_NAME` (`ROLE_NAME`)
) COMMENT '角色表';
DROP TABLE IF EXISTS RESOURCES;
CREATE TABLE RESOURCES (
	ID INT NOT NULL PRIMARY KEY,
	`PATH` VARCHAR(200) NOT NULL UNIQUE COMMENT '资源路径',
	RES_DESC VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci COMMENT '资源路径的描述信息',
	ROLE_ID INT REFERENCES ROLE(ID)
) COMMENT '系统资源路径';
DROP TABLE IF EXISTS ADMIN;
CREATE TABLE ADMIN (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MOBILE VARCHAR(50) NOT NULL UNIQUE COMMENT '管理员手机号',
	EMAIL VARCHAR(50) NOT NULL UNIQUE COMMENT '管理员邮箱',
	`PASSWORD` VARCHAR(50) NOT NULL COMMENT 'MD5密码',
	NICKNAME VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci COMMENT '管理员设置的昵称',
	TRUENAME VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci COMMENT '管理员真实姓名',
	LOCKED NUMERIC(1) DEFAULT 0 COMMENT '是否锁定1:锁定 0：正常',
	SUPER_ADMIN NUMERIC(1) DEFAULT 0 COMMENT '是否是超级管理员1：超级管理员 0：普通管理员'
) COMMENT '管理员表';
DROP TABLE IF EXISTS ADMIN_GROUP;
CREATE TABLE ADMIN_GROUP (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	GROUP_NAME VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL UNIQUE COMMENT '管理员组名称',
	GROUP_DESC VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci COMMENT '管理员组描述' ,
	SORT int DEFAULT 1 COMMENT '排序字段'
) COMMENT '管理员组';
DROP TABLE IF EXISTS ROLE_ADMIN_MIDDLE;
CREATE TABLE ROLE_ADMIN_MIDDLE (
	ROLE_ID INT NOT NULL REFERENCES ROLE(ID),
	ADMIN_ID INT NOT NULL REFERENCES ADMIN(ID),
	PRIMARY KEY (ROLE_ID,ADMIN_ID)
);
DROP TABLE IF EXISTS ADMIN_GROUP_MIDDLE;
CREATE TABLE ADMIN_GROUP_MIDDLE (
	GROUP_ID INT NOT NULL REFERENCES ADMIN_GROUP(ID),
	ADMIN_ID INT NOT NULL REFERENCES ADMIN(ID),
	PRIMARY KEY (GROUP_ID,ADMIN_ID)
);
DROP TABLE IF EXISTS ROLE_ADMIN_GROUP_MIDDLE;
CREATE TABLE ROLE_ADMIN_GROUP_MIDDLE (
	ROLE_ID INT NOT NULL REFERENCES ROLE(ID),
	GROUP_ID INT NOT NULL REFERENCES ADMIN_GROUP(ID),
	PRIMARY KEY (ROLE_ID,GROUP_ID)
);
INSERT INTO ROLE(ROLE_NAME,ROLE_CODE,ROLE_DESC) values ('添加管理员','ROLE_ADD_ADMIN','添加管理员角色权限');